function [stringData]=PrintData(mdb)
    stringData = [ TXPrintData(1,mdb); ...
                   TXPrintData(2,mdb);...
                   TXPrintData(3,mdb) ...
                   ]';
               
%      struct = array2table(stringData);          
end