function str=TXPrintData(num , mdb)
    str = '';
    TXString = strcat('TX',num2str(num));
    if(0 == mdb.master.([TXString,'_select']))
        return;
    end
    
    if(1==mdb.(TXString).stimulus.stimulusSelect.pureTone)
        mode = 'Pure Tone';
    elseif(1==mdb.(TXString).stimulus.stimulusSelect.noise)
        mode = 'Noise';
    elseif(1==mdb.(TXString).stimulus.stimulusSelect.speech)
        mode = 'Speech';
    end
    
    
    str = [TXString,': ',mode,newline,...
           'Active Output: ',num2str(find(mdb.(TXString).transducer.FF.DacVector)),...
           newline];
    if(0==mdb.(TXString).stimulus.burstDuration)
        str = [str ...
               'Duration: Continues' newline];
    else
        str = [str ...
               'Duration: ' num2str(mdb.(TXString).stimulus.burstDuration) ' seconds' newline];
    end
     
    switch mode
        case 'Pure Tone'
            str = [str...
                   'Pure Tone' newline...
                   'Level(db): ' num2str(mdb.(TXString).stimulus.PT.amp) newline...
                   'Frequency (Hz): ' num2str(mdb.(TXString).stimulus.PT.freq) newline...
                   'Phase: ' num2str(mdb.(TXString).stimulus.PT.phase) newline... 
                   'Mod Frequency: ' num2str(mdb.(TXString).stimulus.PT.modFreq) newline...
                   ];
            [FM,AM] = ModulationTypeToFmAmModes(mdb.(TXString).stimulus.PT.modulationType)
            if(FM)
               str = [str...
                      'FM Modulation Index: ' num2str(mdb.(TXString).stimulus.PT.modIndex) newline];
            end
            if(AM)
               str = [str ...
                       'AM Modulation Depth: ' num2str(mdb.(TXString).stimulus.PT.modDepth) newline];
            end

        case 'Noise'
            if(2 == mdb.(TXString).stimulus.noise.source )
                str = [str...
                       'Noise Bandwidth' newline];
            else 
                str = [str...
                       'White Noise' newline];
            end

            str = [str...
                    'Level(db): ' num2str(mdb.(TXString).stimulus.noise.amp) newline...
                    'Phase: ' num2str(mdb.(TXString).stimulus.noise.phase) newline... 
                    ];
            if(2 == mdb.(TXString).stimulus.noise.source )
                str = [str...
                    'Noise Bandwidth:' newline...
                    '  Frequency Center: ' num2str(mdb.(TXString).stimulus.noise.NBCntrFrq) newline...
                    '        Band Width: ' num2str(mdb.(TXString).stimulus.noise.NBBW) newline ];
            end
        case 'Speech'
            str = [str...
                   'Speech/From File ' newline...
                    'Level(db): ' num2str(mdb.(TXString).stimulus.speech.amp) newline...
                    'Phase: ' num2str(mdb.(TXString).stimulus.speech.phase) newline... 
                    'Source: '  mdb.(TXString).stimulus.speech.source newline...
                    ];
    end
str = string(str);
end